cookie:
  expiry_days: 30
  key: some_signature_key # Must be a string
  name: some_cookie_name
credentials:
  usernames:
    neuralninja7:
      email: neuralninja7@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: neuralninja7
      password: bexley@123
      roles:
      - admin
      - editor
      - viewer
oauth2:
  google: # Follow instructions: https://developers.google.com/identity/protocols/oauth2
    client_id: 712357922075-07eii2qkofactvsj0bu9jofa3luto8lh.apps.googleusercontent.com
    client_secret: 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
    redirect_uri: http://localhost:8501
pre-authorized:
  emails:
  - neuralninja7@gmail.com